//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReverseMarket.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReverseMarket.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من نحن.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منصة مبتكرة لربط المشترين بالبائعين.
        /// </summary>
        public static string AboutSubtitle {
            get {
                return ResourceManager.GetString("AboutSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قبول الشروط.
        /// </summary>
        public static string AcceptanceOfTerms {
            get {
                return ResourceManager.GetString("AcceptanceOfTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to باستخدام خدماتنا، فإنك توافق على جميع الشروط والأحكام المذكورة هنا.
        /// </summary>
        public static string AcceptanceText {
            get {
                return ResourceManager.GetString("AcceptanceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نشط.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أضف أول طلب.
        /// </summary>
        public static string AddFirstRequest {
            get {
                return ResourceManager.GetString("AddFirstRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة طلب.
        /// </summary>
        public static string AddRequest {
            get {
                return ResourceManager.GetString("AddRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أضف طلبك الآن.
        /// </summary>
        public static string AddRequestNow {
            get {
                return ResourceManager.GetString("AddRequestNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لوحة التحكم.
        /// </summary>
        public static string AdminPanel {
            get {
                return ResourceManager.GetString("AdminPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إعلان.
        /// </summary>
        public static string Advertisement {
            get {
                return ResourceManager.GetString("Advertisement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جميع الفئات.
        /// </summary>
        public static string AllCategories {
            get {
                return ResourceManager.GetString("AllCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جميع الطلبات.
        /// </summary>
        public static string AllRequests {
            get {
                return ResourceManager.GetString("AllRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض جميع الطلبات.
        /// </summary>
        public static string AllRightsReserved {
            get {
                return ResourceManager.GetString("AllRightsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقبول.
        /// </summary>
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فئة متاحة.
        /// </summary>
        public static string AvailableCategories {
            get {
                return ResourceManager.GetString("AvailableCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رجوع.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العودة للرئيسية.
        /// </summary>
        public static string BackToHome {
            get {
                return ResourceManager.GetString("BackToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كن أول من يضيف طلباً.
        /// </summary>
        public static string BeFirstToAddRequest {
            get {
                return ResourceManager.GetString("BeFirstToAddRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أفضل الفئات.
        /// </summary>
        public static string BestCategories {
            get {
                return ResourceManager.GetString("BestCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر من بين مجموعة واسعة من الفئات.
        /// </summary>
        public static string BestCategoriesSubtitle {
            get {
                return ResourceManager.GetString("BestCategoriesSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أفضل العروض.
        /// </summary>
        public static string BestOffers {
            get {
                return ResourceManager.GetString("BestOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المتاجر تتنافس لتقديم أفضل الأسعار والخدمات.
        /// </summary>
        public static string BestOffersText {
            get {
                return ResourceManager.GetString("BestOffersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string BrowseAvailableRequests {
            get {
                return ResourceManager.GetString("BrowseAvailableRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string BrowseRegisteredStores {
            get {
                return ResourceManager.GetString("BrowseRegisteredStores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصفح الطلبات.
        /// </summary>
        public static string BrowseRequests {
            get {
                return ResourceManager.GetString("BrowseRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إلغاء.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفئة.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قد نقوم بتحديث هذه الشروط من وقت لآخر. استمرار استخدامك يعني موافقتك على التغييرات.
        /// </summary>
        public static string ChangesText {
            get {
                return ResourceManager.GetString("ChangesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغييرات على الشروط.
        /// </summary>
        public static string ChangesToTerms {
            get {
                return ResourceManager.GetString("ChangesToTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خصوصية الأطفال.
        /// </summary>
        public static string ChildrenPrivacy {
            get {
                return ResourceManager.GetString("ChildrenPrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدماتنا غير موجهة للأطفال دون سن 18 عاماً.
        /// </summary>
        public static string ChildrenText {
            get {
                return ResourceManager.GetString("ChildrenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المحافظة.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شكوى.
        /// </summary>
        public static string Complaint {
            get {
                return ResourceManager.GetString("Complaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طلب منجز.
        /// </summary>
        public static string CompletedRequests {
            get {
                return ResourceManager.GetString("CompletedRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل أنت متأكد من الحذف؟.
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اتصل بنا.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نحن هنا لمساعدتك. تواصل معنا في أي وقت.
        /// </summary>
        public static string ContactDescription {
            get {
                return ResourceManager.GetString("ContactDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات التواصل.
        /// </summary>
        public static string ContactInfo {
            get {
                return ResourceManager.GetString("ContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إذا كانت لديك أسئلة حول سياسة الخصوصية، يرجى الاتصال بنا.
        /// </summary>
        public static string ContactPrivacyText {
            get {
                return ResourceManager.GetString("ContactPrivacyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إذا كانت لديك أسئلة حول شروط الاستخدام، يرجى الاتصال بنا.
        /// </summary>
        public static string ContactTermsText {
            get {
                return ResourceManager.GetString("ContactTermsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اتصل بنا.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملفات تعريف الارتباط.
        /// </summary>
        public static string Cookies {
            get {
                return ResourceManager.GetString("Cookies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نستخدم ملفات تعريف الارتباط لتحسين تجربتك على موقعنا.
        /// </summary>
        public static string CookiesText {
            get {
                return ResourceManager.GetString("CookiesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2025 السوق العكسي. جميع الحقوق محفوظة.
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الإنشاء.
        /// </summary>
        public static string CreatedAt {
            get {
                return ResourceManager.GetString("CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حماية البيانات.
        /// </summary>
        public static string DataProtection {
            get {
                return ResourceManager.GetString("DataProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نحن نتخذ إجراءات أمنية مناسبة لحماية معلوماتك الشخصية.
        /// </summary>
        public static string DataProtectionText {
            get {
                return ResourceManager.GetString("DataProtectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاحتفاظ بالبيانات.
        /// </summary>
        public static string DataRetention {
            get {
                return ResourceManager.GetString("DataRetention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التاريخ.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوصف.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اكتشف المنتجات والخدمات.
        /// </summary>
        public static string DiscoverProducts {
            get {
                return ResourceManager.GetString("DiscoverProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المنطقة.
        /// </summary>
        public static string District {
            get {
                return ResourceManager.GetString("District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EnterPhoneToLogin {
            get {
                return ResourceManager.GetString("EnterPhoneToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EnterPhoneWithoutCode {
            get {
                return ResourceManager.GetString("EnterPhoneWithoutCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فيسبوك.
        /// </summary>
        public static string Facebook {
            get {
                return ResourceManager.GetString("Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأسئلة الشائعة.
        /// </summary>
        public static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السوق العكسي هو منصة تربط بين المشترين والبائعين بطريقة عكسية، حيث يضيف العميل طلبه وتتنافس المتاجر لخدمته.
        /// </summary>
        public static string FAQ1Answer {
            get {
                return ResourceManager.GetString("FAQ1Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ما هو السوق العكسي؟.
        /// </summary>
        public static string FAQ1Question {
            get {
                return ResourceManager.GetString("FAQ1Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نعم، إضافة الطلبات وتصفح العروض مجاني تماماً للعملاء.
        /// </summary>
        public static string FAQ2Answer {
            get {
                return ResourceManager.GetString("FAQ2Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل الخدمة مجانية؟.
        /// </summary>
        public static string FAQ2Question {
            get {
                return ResourceManager.GetString("FAQ2Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ForEveryone {
            get {
                return ResourceManager.GetString("ForEveryone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الكامل.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استفسار عام.
        /// </summary>
        public static string GeneralInquiry {
            get {
                return ResourceManager.GetString("GeneralInquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرئيسية.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كيف يعمل السوق العكسي؟.
        /// </summary>
        public static string HowItWorks {
            get {
                return ResourceManager.GetString("HowItWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطوات بسيطة للحصول على ما تريد.
        /// </summary>
        public static string HowItWorksSubtitle {
            get {
                return ResourceManager.GetString("HowItWorksSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كيف نستخدم معلوماتك.
        /// </summary>
        public static string HowWeUseInformation {
            get {
                return ResourceManager.GetString("HowWeUseInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string IAgreeToThe {
            get {
                return ResourceManager.GetString("IAgreeToThe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روابط مهمة.
        /// </summary>
        public static string ImportantLinks {
            get {
                return ResourceManager.GetString("ImportantLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير نشط.
        /// </summary>
        public static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشاركة المعلومات.
        /// </summary>
        public static string InformationSharing {
            get {
                return ResourceManager.GetString("InformationSharing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المعلومات التي نجمعها.
        /// </summary>
        public static string InformationWeCollect {
            get {
                return ResourceManager.GetString("InformationWeCollect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إنستغرام.
        /// </summary>
        public static string Instagram {
            get {
                return ResourceManager.GetString("Instagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string InstantVerification {
            get {
                return ResourceManager.GetString("InstantVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملكية الفكرية.
        /// </summary>
        public static string IntellectualProperty {
            get {
                return ResourceManager.GetString("IntellectualProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حقوق الملكية الفكرية من قاعدة البيانات.
        /// </summary>
        public static string IntellectualPropertyFromDatabase {
            get {
                return ResourceManager.GetString("IntellectualPropertyFromDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جميع المحتويات على الموقع محمية بحقوق الطبع والنشر والعلامات التجارية.
        /// </summary>
        public static string IntellectualPropertyText {
            get {
                return ResourceManager.GetString("IntellectualPropertyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المقدمة.
        /// </summary>
        public static string Introduction {
            get {
                return ResourceManager.GetString("Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تغيير اللغة بنجاح.
        /// </summary>
        public static string LanguageChanged {
            get {
                return ResourceManager.GetString("LanguageChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ في تغيير اللغة.
        /// </summary>
        public static string LanguageError {
            get {
                return ResourceManager.GetString("LanguageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آخر تحديث.
        /// </summary>
        public static string LastUpdated {
            get {
                return ResourceManager.GetString("LastUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نحن نقدم المنصة &quot;كما هي&quot; ولا نتحمل مسؤولية أي خسائر قد تنتج عن الاستخدام.
        /// </summary>
        public static string LiabilityText {
            get {
                return ResourceManager.GetString("LiabilityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدود المسؤولية.
        /// </summary>
        public static string LimitationOfLiability {
            get {
                return ResourceManager.GetString("LimitationOfLiability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جاري التحميل....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جاري تحميل اللغة....
        /// </summary>
        public static string LoadingLanguage {
            get {
                return ResourceManager.GetString("LoadingLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموقع.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بغداد، العراق.
        /// </summary>
        public static string LocationAddress {
            get {
                return ResourceManager.GetString("LocationAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل الدخول.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل الخروج.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرسالة.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إرسال رسالتك بنجاح.
        /// </summary>
        public static string MessageSentSuccess {
            get {
                return ResourceManager.GetString("MessageSentSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسهيل عملية التسوق وتوفير الوقت والجهد للعملاء من خلال جعل المتاجر تتنافس لخدمتهم.
        /// </summary>
        public static string MissionText {
            get {
                return ResourceManager.GetString("MissionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طلباتي.
        /// </summary>
        public static string MyRequests {
            get {
                return ResourceManager.GetString("MyRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التالي.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا توجد بيانات متاحة.
        /// </summary>
        public static string NoDataAvailable {
            get {
                return ResourceManager.GetString("NoDataAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا توجد طلبات حديثة.
        /// </summary>
        public static string NoRecentRequests {
            get {
                return ResourceManager.GetString("NoRecentRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختياري.
        /// </summary>
        public static string Optional {
            get {
                return ResourceManager.GetString("Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مزايانا.
        /// </summary>
        public static string OurAdvantages {
            get {
                return ResourceManager.GetString("OurAdvantages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رسالتنا.
        /// </summary>
        public static string OurMission {
            get {
                return ResourceManager.GetString("OurMission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رؤيتنا.
        /// </summary>
        public static string OurVision {
            get {
                return ResourceManager.GetString("OurVision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قيد المراجعة.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الكامل.
        /// </summary>
        public static string PersonalInfo1 {
            get {
                return ResourceManager.GetString("PersonalInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهاتف.
        /// </summary>
        public static string PersonalInfo2 {
            get {
                return ResourceManager.GetString("PersonalInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني.
        /// </summary>
        public static string PersonalInfo3 {
            get {
                return ResourceManager.GetString("PersonalInfo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان والموقع.
        /// </summary>
        public static string PersonalInfo4 {
            get {
                return ResourceManager.GetString("PersonalInfo4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المعلومات الشخصية.
        /// </summary>
        public static string PersonalInformation {
            get {
                return ResourceManager.GetString("PersonalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الهاتف.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغييرات السياسة.
        /// </summary>
        public static string PolicyChanges {
            get {
                return ResourceManager.GetString("PolicyChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قد نقوم بتحديث هذه السياسة من وقت لآخر. سنخطرك بأي تغييرات جوهرية.
        /// </summary>
        public static string PolicyChangesText {
            get {
                return ResourceManager.GetString("PolicyChangesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السابق.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سياسة الخصوصية.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملف الشخصي.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاحتيال أو التضليل.
        /// </summary>
        public static string Prohibited1 {
            get {
                return ResourceManager.GetString("Prohibited1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتهاك حقوق الملكية الفكرية.
        /// </summary>
        public static string Prohibited2 {
            get {
                return ResourceManager.GetString("Prohibited2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نشر فيروسات أو برامج ضارة.
        /// </summary>
        public static string Prohibited3 {
            get {
                return ResourceManager.GetString("Prohibited3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التشويش على الخدمة أو إساءة استخدامها.
        /// </summary>
        public static string Prohibited4 {
            get {
                return ResourceManager.GetString("Prohibited4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأنشطة المحظورة.
        /// </summary>
        public static string ProhibitedActivities {
            get {
                return ResourceManager.GetString("ProhibitedActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تشفير البيانات الحساسة.
        /// </summary>
        public static string Protection1 {
            get {
                return ResourceManager.GetString("Protection1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوصول المحدود للموظفين المصرح لهم.
        /// </summary>
        public static string Protection2 {
            get {
                return ResourceManager.GetString("Protection2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المراقبة المستمرة للأنظمة.
        /// </summary>
        public static string Protection3 {
            get {
                return ResourceManager.GetString("Protection3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الطلبات المضافة مؤخراً.
        /// </summary>
        public static string RecentRequests {
            get {
                return ResourceManager.GetString("RecentRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آخر الطلبات المتاحة من العملاء.
        /// </summary>
        public static string RecentRequestsSubtitle {
            get {
                return ResourceManager.GetString("RecentRequestsSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متجر مسجل.
        /// </summary>
        public static string RegisteredStores {
            get {
                return ResourceManager.GetString("RegisteredStores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RegisterYourStore {
            get {
                return ResourceManager.GetString("RegisterYourStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن تكون فوق 18 عاماً للتسجيل.
        /// </summary>
        public static string RegistrationRule1 {
            get {
                return ResourceManager.GetString("RegistrationRule1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقديم معلومات صحيحة ودقيقة.
        /// </summary>
        public static string RegistrationRule2 {
            get {
                return ResourceManager.GetString("RegistrationRule2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحفاظ على سرية كلمة المرور.
        /// </summary>
        public static string RegistrationRule3 {
            get {
                return ResourceManager.GetString("RegistrationRule3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدم مشاركة الحساب مع الآخرين.
        /// </summary>
        public static string RegistrationRule4 {
            get {
                return ResourceManager.GetString("RegistrationRule4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرفوض.
        /// </summary>
        public static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الطلبات.
        /// </summary>
        public static string Requests {
            get {
                return ResourceManager.GetString("Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مطلوب.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استخدام الموقع بشكل قانوني ومسؤول.
        /// </summary>
        public static string Responsibility1 {
            get {
                return ResourceManager.GetString("Responsibility1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدم نشر محتوى مسيء أو غير قانوني.
        /// </summary>
        public static string Responsibility2 {
            get {
                return ResourceManager.GetString("Responsibility2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to احترام حقوق المستخدمين الآخرين.
        /// </summary>
        public static string Responsibility3 {
            get {
                return ResourceManager.GetString("Responsibility3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحديث معلومات الحساب بانتظام.
        /// </summary>
        public static string Responsibility4 {
            get {
                return ResourceManager.GetString("Responsibility4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نحتفظ بمعلوماتك طالما كان حسابك نشطاً أو حسب الحاجة لتقديم خدماتنا.
        /// </summary>
        public static string RetentionText {
            get {
                return ResourceManager.GetString("RetentionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوصول إلى بياناتك الشخصية.
        /// </summary>
        public static string Right1 {
            get {
                return ResourceManager.GetString("Right1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصحيح المعلومات غير الدقيقة.
        /// </summary>
        public static string Right2 {
            get {
                return ResourceManager.GetString("Right2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف حسابك ومعلوماتك.
        /// </summary>
        public static string Right3 {
            get {
                return ResourceManager.GetString("Right3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاعتراض على معالجة بياناتك.
        /// </summary>
        public static string Right4 {
            get {
                return ResourceManager.GetString("Right4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأمان والثقة.
        /// </summary>
        public static string SafetyTrust {
            get {
                return ResourceManager.GetString("SafetyTrust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جميع المتاجر مُراجعة ومُعتمدة من قبلنا.
        /// </summary>
        public static string SafetyTrustText {
            get {
                return ResourceManager.GetString("SafetyTrustText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عميل راضي.
        /// </summary>
        public static string SatisfiedCustomers {
            get {
                return ResourceManager.GetString("SatisfiedCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بحث.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SearchInStoreNameOrDescription {
            get {
                return ResourceManager.GetString("SearchInStoreNameOrDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SearchInTitleOrDescription {
            get {
                return ResourceManager.GetString("SearchInTitleOrDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ابحث عن طلب معين....
        /// </summary>
        public static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SecureAndProtected {
            get {
                return ResourceManager.GetString("SecureAndProtected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر الموضوع.
        /// </summary>
        public static string SelectSubject {
            get {
                return ResourceManager.GetString("SelectSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرسال رسالة.
        /// </summary>
        public static string SendMessage {
            get {
                return ResourceManager.GetString("SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مع المتاجر المعتمدة فقط للرد على طلباتك.
        /// </summary>
        public static string Sharing1 {
            get {
                return ResourceManager.GetString("Sharing1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عند الطلب القانوني من السلطات.
        /// </summary>
        public static string Sharing2 {
            get {
                return ResourceManager.GetString("Sharing2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مع مقدمي الخدمات الموثوقين.
        /// </summary>
        public static string Sharing3 {
            get {
                return ResourceManager.GetString("Sharing3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نحن لا نبيع أو نؤجر معلوماتك الشخصية لأطراف ثالثة.
        /// </summary>
        public static string SharingText {
            get {
                return ResourceManager.GetString("SharingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منصة تربط العملاء بالمتاجر في العراق.
        /// </summary>
        public static string SiteDescription {
            get {
                return ResourceManager.GetString("SiteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السوق العكسي.
        /// </summary>
        public static string SiteName {
            get {
                return ResourceManager.GetString("SiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مواقع التواصل الاجتماعي.
        /// </summary>
        public static string SocialMedia {
            get {
                return ResourceManager.GetString("SocialMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ابدأ الآن.
        /// </summary>
        public static string StartNow {
            get {
                return ResourceManager.GetString("StartNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحالة.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اكتب تفاصيل ما تحتاجه بوضوح.
        /// </summary>
        public static string Step1Description {
            get {
                return ResourceManager.GetString("Step1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أضف طلبك.
        /// </summary>
        public static string Step1Title {
            get {
                return ResourceManager.GetString("Step1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سيتم مراجعة طلبك والموافقة عليه.
        /// </summary>
        public static string Step2Description {
            get {
                return ResourceManager.GetString("Step2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتظر الموافقة.
        /// </summary>
        public static string Step2Title {
            get {
                return ResourceManager.GetString("Step2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ستحصل على عروض من المتاجر المختصة.
        /// </summary>
        public static string Step3Description {
            get {
                return ResourceManager.GetString("Step3Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المتاجر تتواصل معك.
        /// </summary>
        public static string Step3Title {
            get {
                return ResourceManager.GetString("Step3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قارن العروض واختر الأنسب لك.
        /// </summary>
        public static string Step4Description {
            get {
                return ResourceManager.GetString("Step4Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر الأفضل.
        /// </summary>
        public static string Step4Title {
            get {
                return ResourceManager.GetString("Step4Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المتاجر.
        /// </summary>
        public static string Stores {
            get {
                return ResourceManager.GetString("Stores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string StoresDirectory {
            get {
                return ResourceManager.GetString("StoresDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموضوع.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرسال.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نجاح.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اقتراح.
        /// </summary>
        public static string Suggestion {
            get {
                return ResourceManager.GetString("Suggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشكلة تقنية.
        /// </summary>
        public static string TechnicalIssue {
            get {
                return ResourceManager.GetString("TechnicalIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إنهاء الخدمة.
        /// </summary>
        public static string TerminationOfService {
            get {
                return ResourceManager.GetString("TerminationOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نحتفظ بالحق في إنهاء أو تعليق حسابك في حالة انتهاك الشروط.
        /// </summary>
        public static string TerminationText {
            get {
                return ResourceManager.GetString("TerminationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شروط الاستخدام من قاعدة البيانات.
        /// </summary>
        public static string TermsFromDatabase {
            get {
                return ResourceManager.GetString("TermsFromDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرحباً بك في السوق العكسي. باستخدامك لهذا الموقع، فإنك توافق على الالتزام بشروط الاستخدام التالية.
        /// </summary>
        public static string TermsIntroText {
            get {
                return ResourceManager.GetString("TermsIntroText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شروط الاستخدام.
        /// </summary>
        public static string TermsOfUse {
            get {
                return ResourceManager.GetString("TermsOfUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توفير الوقت.
        /// </summary>
        public static string TimeSaving {
            get {
                return ResourceManager.GetString("TimeSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بدلاً من البحث في عشرات المتاجر، المتاجر تأتي إليك.
        /// </summary>
        public static string TimeSavingText {
            get {
                return ResourceManager.GetString("TimeSavingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تويتر.
        /// </summary>
        public static string Twitter {
            get {
                return ResourceManager.GetString("Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ التحديث.
        /// </summary>
        public static string UpdatedAt {
            get {
                return ResourceManager.GetString("UpdatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقديم وتحسين خدماتنا.
        /// </summary>
        public static string UseInfo1 {
            get {
                return ResourceManager.GetString("UseInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التواصل معك بخصوص طلباتك.
        /// </summary>
        public static string UseInfo2 {
            get {
                return ResourceManager.GetString("UseInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرسال إشعارات وتحديثات.
        /// </summary>
        public static string UseInfo3 {
            get {
                return ResourceManager.GetString("UseInfo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحليل وتحسين تجربة المستخدم.
        /// </summary>
        public static string UseInfo4 {
            get {
                return ResourceManager.GetString("UseInfo4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حماية حقوقنا القانونية.
        /// </summary>
        public static string UseInfo5 {
            get {
                return ResourceManager.GetString("UseInfo5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل المستخدم.
        /// </summary>
        public static string UserRegistration {
            get {
                return ResourceManager.GetString("UserRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسؤوليات المستخدم.
        /// </summary>
        public static string UserResponsibilities {
            get {
                return ResourceManager.GetString("UserResponsibilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string VerificationCodeViaWhatsApp {
            get {
                return ResourceManager.GetString("VerificationCodeViaWhatsApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض الكل.
        /// </summary>
        public static string ViewAll {
            get {
                return ResourceManager.GetString("ViewAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض جميع الطلبات.
        /// </summary>
        public static string ViewAllRequests {
            get {
                return ResourceManager.GetString("ViewAllRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض التفاصيل.
        /// </summary>
        public static string ViewDetails {
            get {
                return ResourceManager.GetString("ViewDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أن نكون المنصة الرائدة في العراق لربط المشترين بالبائعين من خلال نموذج السوق العكسي المبتكر.
        /// </summary>
        public static string VisionText {
            get {
                return ResourceManager.GetString("VisionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرحباً بك في السوق العكسي.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أضف طلبك ودع المتاجر تتنافس لخدمتك.
        /// </summary>
        public static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to واتساب.
        /// </summary>
        public static string WhatsApp {
            get {
                return ResourceManager.GetString("WhatsApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حقوقك.
        /// </summary>
        public static string YourRights {
            get {
                return ResourceManager.GetString("YourRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يوتيوب.
        /// </summary>
        public static string YouTube {
            get {
                return ResourceManager.GetString("YouTube", resourceCulture);
            }
        }
    }
}
